a = 5
b = 3
c = 72
d = 304
s1 = 'string'
pi = 3.141592

print('{0:-^48}'.format(' % 사용 '))
print('%d + %d = %d' % (a, b, a + b))
print('%d + %d = %d' % (c, d, c + d))
print('*' * 16)
print('%2d + %2d = %2d' % (a, b, a + b))
print('%2d + %2d = %2d' % (c, d, c + d))
print('*' * 16)
print('%03d + %03d = %03d' % (a, b, a + b))
print('%03d + %03d = %03d' % (c, d, c + d))
print('*' * 16)
print('string: %s' % s1)
print('string: [%10s]' % s1)
print('string: [%-10s]' % s1)
print('*' * 16)
print('pi = %f' % pi)
print('pi = %.3f' % pi)
print('pi = %10.3f' % pi)
print('%d = 0x%04X' % (d, d))
print()

print('{0:-^48}'.format(' Use format() '))
print('{0} + {1} = {2}'.format(a, b, a + b))
print('{0} + {1} = {2}'.format(c, d, c + d))
print('*' * 16)
print('{0:2} + {1:2} = {2:2}'.format(a, b, a + b))
print('{0:2} + {1:2} = {2:2}'.format(c, d, c + d))
print('*' * 16)
print('{0:03} + {1:03} = {2:03}'.format(a, b, a + b))
print('{0:03} + {1:03} = {2:03}'.format(c, d, c + d))
print()

print('{0:-^48}'.format(' Use f formatting '))
print(f'{a} + {b} = {a + b}')
print(f'{c} + {d} = {c + d}')
print('*' * 16)
print(f'{a:2} + {b:2} = {a + b:2}')
print(f'{c:2} + {d:2} = {c + d:2}')
print('*' * 16)
print(f'{a:03} + {b:03} = {a + b:03}')
print(f'{c:03} + {d:03} = {c + d:03}')
print('*' * 16)
print(f'string: {s1}')
print(f'string: {s1:<10}')
print(f'string: {s1:>10}')
print('*' * 16)
print(f'pi: {pi}')
print(f'pi: {pi:.3f}')
print(f'pi: {pi:8.3f}')
print(f'pi: {pi:08.3f}')
print('*' * 16)
print(f'{d} = 0x{d:04X}')